# Generated by Django 4.0.4 on 2022-05-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField(max_length=200)),
                ('autor', models.CharField(max_length=20)),
                ('criado', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
            ],
        ),
    ]
