# Generated by Django 4.0.4 on 2022-05-29 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ranking', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('topicos', models.TextField()),
                ('etcs', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PontuacaoQuizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pontuacao', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorPratica',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('linkLusofona', models.URLField(blank=True)),
                ('linkLinkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorTeorica',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('linkLusofona', models.URLField(blank=True)),
                ('linkLinkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='autor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
                ('cadeira', models.ManyToManyField(related_name='tem', to='portfolio.cadeira')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_pratica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.professorpratica'),
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.professorteorica'),
        ),
    ]
