# Generated by Django 4.0.4 on 2022-06-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('titulo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('autor1', models.CharField(max_length=50)),
                ('autor2', models.CharField(max_length=50)),
                ('orientador', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('resumo', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
