# Generated by Django 4.0.4 on 2022-05-18 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_pontuacaoquizz_alter_post_autor_alter_post_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('imagem', models.ImageField(upload_to='')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('linkLusofona', models.URLField(blank=True)),
                ('linkLinkedin', models.URLField(blank=True)),
                ('projetos', models.ManyToManyField(related_name='apoia', to='portfolio.projeto')),
                ('projetos_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('ranking', models.IntegerField()),
                ('ano', models.IntegerField()),
                ('topicos', models.TextField()),
                ('etcs', models.IntegerField()),
                ('docente', models.ManyToManyField(related_name='leciona', to='portfolio.professor')),
                ('docente_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.professor')),
                ('projetos', models.ManyToManyField(related_name='tem', to='portfolio.projeto')),
            ],
        ),
    ]
