# Generated by Django 4.0.4 on 2022-06-12 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_tfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('criador', models.CharField(max_length=50)),
                ('dataLancamento', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('imagem', models.ImageField(upload_to='')),
            ],
        ),
    ]
