# Generated by Django 4.0.4 on 2022-05-24 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_projeto_professor_cadeira'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadeira',
            old_name='docente_fk',
            new_name='docente_teorica',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='id',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='projetos',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='projetos_fk',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='id',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docentes_praticas',
            field=models.ManyToManyField(related_name='apoia', to='portfolio.professor'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.cadeira'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='professor',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='nome',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
