# Generated by Django 4.0.4 on 2022-05-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_rename_docente_fk_cadeira_docente_teorica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='cadeira',
        ),
        migrations.AddField(
            model_name='projeto',
            name='cadeira',
            field=models.ManyToManyField(related_name='tem', to='portfolio.cadeira'),
        ),
    ]
