# Generated by Django 4.0.4 on 2022-05-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_projeto_cadeira_projeto_cadeira'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontuacaoquizz',
            name='pontuacao',
            field=models.IntegerField(),
        ),
    ]
