# Generated by Django 4.0.4 on 2022-05-29 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_pontuacaoquizz_pontuacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorTeorica',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('linkLusofona', models.URLField(blank=True)),
                ('linkLinkedin', models.URLField(blank=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='Professor',
            new_name='ProfessorPratica',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='docentes_praticas',
        ),
        migrations.AddField(
            model_name='cadeira',
            name='docente_pratica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.professorpratica'),
        ),
        migrations.AlterField(
            model_name='cadeira',
            name='docente_teorica',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='portfolio.professorteorica'),
        ),
    ]
