# Generated by Django 4.0.4 on 2022-05-29 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_professorteorica_rename_professor_professorpratica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeira',
            name='docente_pratica',
        ),
        migrations.RemoveField(
            model_name='cadeira',
            name='docente_teorica',
        ),
    ]
